PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ifc: <http://standards.buildingsmart.org/IFC/DEV/IFC2x3/TC1/OWL#>

SELECT DISTINCT ?projectUri ?unitAssignmentUri ?unitUri ?unitType ?unitMeasure ?unitPrefix
WHERE {
      ?unitUri ifc:unitType_IfcNamedUnit ?unitType .
      ?unitUri ifc:name_IfcSIUnit ?unitMeasure .
      OPTIONAL { ?unitUri ifc:prefix_IfcSIUnit ?unitPrefix . }
      OPTIONAL {
               ?projectUri a ifc:IfcProject .
               ?projectUri ifc:unitsInContext_IfcProject ?unitAssignmentUri .
               ?unitAssignmentUri ifc:units_IfcUnitAssignment ?unitUri .
               }
}
