# TODO units are not yet retrieved for the individual properties, only the project units are used (see extract_projectunits.rq for the query)
# this is due to the fact that none of our available ifc files have set the (optional) unit in the properties and thus the project units will be used
# TODO: SOMEHOW I THINK IFC4 SPLITS THE PROPERTIES BASED ON THE TYPE:

PREFIX express: <https://w3id.org/express#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ifc:     <http://standards.buildingsmart.org/IFC/DEV/IFC4/ADD2_TC1/OWL#>

SELECT DISTINCT ?propName ?propType
WHERE {
          ?propUri ifc:name_IfcProperty ?propNameUri.
          ?propUri ifc:nominalValue_IfcPropertySingleValue ?propTypeUri .
          ?propTypeUri a ?propType .
          ?propNameUri
          a                       ifc:IfcIdentifier ;
          express:hasString       ?propName ;
      }

# select distinct ?propName ?propType where {
#     {
#         ?uri a ifc:IfcQuantityLength.
#         ?uri ifc:name_IfcPhysicalQuantity ?labelUri .
#         ?uri ifc:lengthValue_IfcQuantityLength ?measureUri .
#         ?labelUri express:hasString	?propName .
#         ?measureUri rdf:type ?propType ;
#     }
#     UNION
#     {
#         ?uri a ifc:IfcQuantityVolume.
#         ?uri ifc:name_IfcPhysicalQuantity ?labelUri .
#         ?uri ifc:volumeValue_IfcQuantityVolume ?measureUri .
#         ?labelUri express:hasString	?propName .
#         ?measureUri rdf:type ?propType ;
#     }
#     UNION
#     {
#         ?uri a ifc:IfcQuantityArea.
#         ?uri ifc:name_IfcPhysicalQuantity ?labelUri .
#         ?uri ifc:areaValue_IfcQuantityArea ?measureUri .
#         ?labelUri express:hasString	?propName .
#         ?measureUri rdf:type ?propType ;
#     }
# }
